### PR TITLE
Copy without newline (at least on OSX)

### PR DESCRIPTION
**Pull request by tomsmeding**
The version on master (5186a53) appends a newline when copying. This is because
of the usage of `echo`. This commit attempts to fix that by directly supplying
the input to the system copy program. Tested on OSX.

### CODE REVIEW

**Comment by tomsmeding** [comment]
I see that there has been more activity on this issue elsewhere; on OSX, the master code didn't work for me. This works, though, and I think is more resilient to weird shell semantics on other operating systems because we don't rely on the piping syntax, for example.

**Comment by tomsmeding** [comment]
The problem is that the `format` function has become a bit obsolete in this implementation, so the tests are commented out...

**Comment by jonschlinkert** [comment]
thanks!

> The problem is that the format function has become a bit obsolete in this implementation, so the tests are commented out...

let's just delete that code then. I think you're approach is good. much appreciated!

**Comment by tomsmeding** [comment]
Is this ready to be merged or does something still need to be cleaned up?

**Comment by jonschlinkert** [comment]
sorry for the lack of follow up. would you mind removing the commented tests if they're irrelevant now anyway? then I can merge in.

**Comment by tomsmeding** [comment]
No problem! :) Here we go.

**Comment by jonschlinkert** [comment]
thanks!

**Comment by jonschlinkert** [comment]
Published and [tagged as 0.2.0](https://github.com/jonschlinkert/to-clipboard/releases/tag/0.2.0). thanks again!

**Comment by tomsmeding** [comment]
Np; wanted to do it myself but found your library, and thought I might make this better :)

**Comment by jonschlinkert** [comment]
you did, thanks! I really appreciate it!

**Pull request merged**
